version: "3.4"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    image: ${IMAGE_NAME}
    environment:
      - DATABASE_URL=postgres://postgres:password@db
      - RAILS_ENV
      - RACK_ENV
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL
      - AUTH_SECRET_TOKEN
    build:
      context: .
      args:
        - BUNDLE_WITHOUT="${BUNDLE_WITHOUT}"
        - BUNDLER_VERSION=2.1.4
        - FOLDERS_TO_REMOVE=""
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ruby-bundle:/usr/local/bundle
      - node-modules:/usr/local/node_modules
    command: bin/docker-entrypoint

volumes:
  ruby-bundle:
  node-modules:
  db-data:
